### PR TITLE
Various suggestions and fixes

### PR DESCRIPTION
**Pull request by cozybear-dev**
Hi @reverse-hash,

This is my current branch I run personally. I run it on a ARM based board, and ran into some issues which I fixed. Amongst other minor things. I'm aware you can't merge it as is, but wanted to share it already like this just so you're aware.

- I added (partial) instructions to configure your own credentials
  - https://github.com/reverse-hash/bitcoin-full-node-with-docker/issues/3
- I added a (true) multi arch container for the tor proxy (Tor browser is not support for Linux aarch64)
  - Your current dockerfile is bound to what tor releases themselves. I basically copied the https://github.com/cmehay/docker-tor-hidden-service Dockerfile and stripped all the bloat and changed some formatting.
- For some reason the proxy arg "tor" - so the hostname - is not accepted when I'm running the bitcoind container. Hence updating it with the IP itself.
- I also noticed that you hadn't disabled the dns traffic in the config, such requests go over clearnet. To be fair, if you really want to be tor only, you'd need to proxy in a different way anyways - but why not use the option if it's available.

### CODE REVIEW

**Comment by cozybear-dev** [comment]
You don't even need to do anything for custom onion addresses I see, it's already location in the volume that is mounted. So just enable the hidden services, tor will create them for you. Shut everything down, replace the files - done.

**Comment by reverse-hash** [comment]
Hi @cozybear-dev,  I will try to check everything during the weekend and the next week. Thanks a lot for all the effort and time for sharing. 

I leave this open in case I have any questions.

**Comment by cozybear-dev** [comment]
Hi,

Another update on my setup;

My data disk is a HDD, which is quite slow for the whole bootstrapping (loading all blocks). I read online you can improve the process by locating the relevant dirs at faster storage - which I did and it does.

Blocks is the data heavy part, which is on the HDD. The rest of the data is located on my fast sdcard, with a symlink inside the directory to the block location on the HDD. Using volumes in this order + with the symlink; you can mount overlapping volumes to the container without creating conflicts.

The indexing performance increased using this method. Disk read speeds are now 400% faster.

volumes:
      - $BITCOIN_BLOCKS:/home/bitcoin/.bitcoin/blocks
      - $BITCOIN_DATA:/home/bitcoin/.bitcoin

**Comment by cozybear-dev** [comment]
This looks as follows;

image

**Comment by reverse-hash** [comment]
Hi @cozybear-dev, following your suggestions I updated the project to create Tor from sources. I've pending to verify the signature of the tags, but it's working.

In: _I also noticed that you hadn't disabled the dns traffic in the config, such requests go over clearnet. To be fair, if you really want to be tor only, you'd need to proxy in a different way anyways - but why not use the option if it's available._

Do you mean in bitcoind.d? I've updated the config files to set dns=0 and dnsseed=0, I hope we were missing these parameters. Let me know if I'm wrong.

I will try to continue investigating a bit the rest of thigs you were sugesting. Regards.

**Comment by cozybear-dev** [comment]
Yes, that was what my comment was regarding.

I ended up not using it altogether as I don't require Tor only and want the additional integrity garuantees (eclipse attack vector) by also connecting to clearnet nodes.

**Comment by reverse-hash** [comment]
Already integrated in main branch. Thanks Cozybear. Closing.

**Pull request closed without merging**
